# Site wide configuration

title: johnnyo.org
description:
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale:
url:  http://blog.johnnyo.org


# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner: 
  name:  JohnnyO
  email:
  twitter:  JohnnyOdotOrg
  google:
    ad-client: 
    ad-slot: 
  bio: Just another random guy rambling on the internet.  I wouldn't trust anything he says.
  avatar: johnnyo.jpg # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
